/* ============ Print House — catálogo de produtos ============
   Edite aqui suas categorias, produtos e variações (opção + preço). */

/* Versão do catálogo: aumente em 1 sempre que alterar este arquivo.
   Edições salvas pelo painel admin em versões antigas são descartadas
   automaticamente, para que as novidades daqui sempre apareçam. */
/* Aviso de arte para produtos de sublimação completa (uniformes, dry fit etc.):
   a arte é criada pela designer da gráfica; o cliente não envia arte pronta. */
const ARTE_SUBLIMACAO = 'A arte é criada por uma <strong>designer profissional da Print House</strong> — você <strong>não precisa enviar arte pronta</strong>. Se quiser, envie apenas a sua <strong>logo ou uma referência</strong> pelo WhatsApp; nós desenvolvemos a arte e você tem direito a até <strong>3 alterações</strong> antes da produção.';

const CATALOGO_VERSAO = 79;

/* Produtos que aparecem em mais de uma categoria são definidos uma única
   vez aqui e referenciados nas categorias — sem duplicar dados. */

const copoCuia = {
  emoji: '🧉', bg: 'linear-gradient(135deg,#e2e8f0,#94a3b8)', badge: 'Novo',
  imagem: 'img/copo-cuia-laser.webp',
  nome: 'Copo Cuia com Tampa em Acrílico 360ml',
  spec: 'Metal · tampa acrílica · gravação a laser 4x0 (4x4 cm) ou estampa em DTF',
  /* Produto com lista de combinações: o cliente escolhe a quantidade de
     cada personalização. O preço unitário segue a faixa da quantidade
     total de copos ("min" = a partir de quantas unidades vale o preço). */
  opcoesCombinacao: [
    { nome: 'Gravação a Laser', imagem: 'img/copo-cuia-laser.webp', faixas: [
      { min: 1, preco: 59.90 },
      { min: 5, preco: 55.90 },
    ] },
    { nome: 'Estampa em DTF', imagem: 'img/copo-cuia-dtf.webp', faixas: [
      { min: 1, preco: 55.90 },
    ] },
  ],
};

const copoTermico = {
  emoji: '☕', bg: 'linear-gradient(135deg,#ddd6fe,#7c3aed)', badge: 'Novo',
  nome: 'Copo Térmico Inox 500ml', spec: 'Gravação a laser 4x0 · mantém a temperatura',
  variacoes: [
    { label: '25 un', preco: 549.90 },
    { label: '50 un', preco: 999.90 },
  ],
};

const copoInoxColorido = {
  emoji: '🥛', bg: 'linear-gradient(135deg,#f1f5f9,#94a3b8)', badge: 'Novo',
  imagem: 'img/copo-termico-inox.webp',
  nome: 'Copo Térmico Aço Inox',
  spec: 'Aço inox · gravação a laser 4x0 (4x10 cm) · 10 cores',
  precoUnitario: 49.90,
  minimo: 1,
  cores: ['Laranja', 'Preto', 'Azul Marinho', 'Branco', 'Marrom', 'Pink', 'Rosa Claro', 'Tiffany', 'Verde Militar', 'Vermelho'],
};

const garrafaInox750 = {
  emoji: '🍶', bg: 'linear-gradient(135deg,#fed7aa,#ea580c)', badge: 'Novo',
  imagem: 'img/garrafa-inox-750.webp',
  nome: 'Garrafa de Inox 750ml Opus',
  spec: 'Aço inox · gravação a laser 4x0 (4x10 cm) · 7 cores',
  precoUnitario: 69.90,
  minimo: 1,
  cores: ['Preto', 'Laranja', 'Branco', 'Vermelho', 'Rosa', 'Azul', 'Prata'],
};

const squeezeFosca = {
  emoji: '🧴', bg: 'linear-gradient(135deg,#bae6fd,#0369a1)', badge: 'Novo',
  nome: 'Squeeze Fosca 600ml',
  spec: 'Metal fosco · gravação a laser 4x0 (4x10 cm) · 6 cores',
  precoUnitario: 49.90,
  minimo: 1,
  cores: ['Preto', 'Verde', 'Vermelho', 'Rosa', 'Azul', 'Prata'],
};

const kitChurrasco = {
  bg: 'linear-gradient(135deg,#fca5a5,#7f1d1d)', badge: 'Novo',
  imagem: 'img/kit-churrasco.webp',
  nome: 'Kit Churrasco',
  spec: 'Estojo nylon + talheres aço inox · gravação a laser + DTF rígido',
  variacoes: [
    { label: '1 kit', preco: 95.90 },
    { label: '5 kits (Promoção)', preco: 335.00 },
  ],
};

const camisetaDtf = {
  bg: 'linear-gradient(135deg,#ddd6fe,#8b5cf6)', badge: 'Promoção',
  imagem: 'img/camiseta-dtf.webp',
  imagens: ['img/camiseta-dtf.webp', 'img/camiseta-dtf-costas.webp'],
  nome: 'Camiseta DTF UV',
  spec: 'Algodão · estampa DTF UV · feminina ou masculina · tamanhos P ao GG · cores conforme disponibilidade em estoque',
  grupoLabel: 'Impressão', opcaoLabel: 'Tamanho',
  extra: { label: 'Modelo', opcoes: ['Feminino', 'Masculino'] },
  coresLabel: 'Cor',
  coresEstampa: ['Preta', 'Branca', 'Vermelha', 'Azul Marinho', 'Amarelo'],
  tamanhos: {
    'Colorido só frente': [
      { label: 'P', preco: 39.90 },
      { label: 'M', preco: 39.90 },
      { label: 'G', preco: 39.90 },
      { label: 'GG', preco: 39.90 },
    ],
    'Colorido frente e verso (promoção)': [
      { label: 'P', preco: 49.90 },
      { label: 'M', preco: 49.90 },
      { label: 'G', preco: 49.90 },
      { label: 'GG', preco: 49.90 },
    ],
  },
};

/* Camisa Copa (mesmas faixas de preço para todos os tamanhos) */
const FAIXAS_CAMISA_COPA = [
  { label: '1 un', preco: 169.90 },
  { label: '5 un', preco: 838.90 },
  { label: '10 un', preco: 1660.90 },
  { label: '20 un', preco: 3291.90 },
  { label: '30 un', preco: 4890.90 },
  { label: '40 un', preco: 6457.90 },
  { label: '50 un', preco: 7995.90 },
  { label: '100 un', preco: 15837.90 },
];
const camisaCopa = {
  bg: 'linear-gradient(135deg,#fde047,#16a34a)', badge: 'Novo', destaque: true,
  nome: 'Camisa Copa Personalizada',
  arteRestrita: ARTE_SUBLIMACAO,
  distribuirTamanhos: true, unidade: 'camisa', unidadePlural: 'camisas',
  spec: 'Tecido Profit · leve, confortável e resistente · tamanhos P ao XL4 · escolha o tamanho e a quantidade',
  prazo: 7,
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
    'P': FAIXAS_CAMISA_COPA,
    'M': FAIXAS_CAMISA_COPA,
    'G': FAIXAS_CAMISA_COPA,
    'GG': FAIXAS_CAMISA_COPA,
    'XL1': FAIXAS_CAMISA_COPA,
    'XL2': FAIXAS_CAMISA_COPA,
    'XL3': FAIXAS_CAMISA_COPA,
    'XL4': FAIXAS_CAMISA_COPA,
  },
};

const ecobagPersonalizada = {
  bg: 'linear-gradient(135deg,#d9f99d,#4d7c0f)', badge: 'Novo',
  imagem: 'img/ecobag-personalizada.webp',
  nome: 'Ecobag Personalizada',
  spec: 'Tecido microfibra · colorido só frente · 30x30 cm · com ou sem velcro',
  variacoes: [
    { label: '5 un · sem Velcro', preco: 97.90 },
    { label: '5 un · com Velcro Total', preco: 132.90 },
    { label: '10 un · sem Velcro', preco: 179.90 },
    { label: '10 un · com Velcro Total', preco: 215.90 },
    { label: '25 un · sem Velcro', preco: 412.90 },
    { label: '25 un · com Velcro Total', preco: 447.90 },
    { label: '50 un · sem Velcro', preco: 749.90 },
    { label: '50 un · com Velcro Total', preco: 785.90 },
    { label: '100 un · sem Velcro', preco: 1424.90 },
    { label: '100 un · com Velcro Total', preco: 1460.90 },
  ],
};

const toalhaBanho = {
  bg: 'linear-gradient(135deg,#bae6fd,#0284c7)', badge: 'Novo',
  imagem: 'img/toalha-banho.webp',
  nome: 'Toalha de Banho Personalizada',
  spec: 'Atoalhado poliéster · colorido só frente',
  variacoes: [
    { label: '1 un', preco: 52.90 },
    { label: '5 un', preco: 254.90 },
    { label: '10 un', preco: 494.90 },
    { label: '25 un', preco: 1219.90 },
    { label: '50 un', preco: 2419.90 },
    { label: '100 un', preco: 4838.90 },
    { label: '200 un', preco: 9600.90 },
    { label: '500 un', preco: 23775.90 },
    { label: '1.000 un', preco: 47250.90 },
  ],
};

const toalhaRosto = {
  bg: 'linear-gradient(135deg,#a5f3fc,#0891b2)', badge: 'Novo',
  nome: 'Toalha de Rosto Personalizada',
  spec: 'Atoalhado poliéster 290g · colorido só frente · 40x65 cm',
  variacoes: [
    { label: '1 un', preco: 29.90 },
    { label: '5 un', preco: 134.90 },
    { label: '10 un', preco: 239.90 },
    { label: '25 un', preco: 524.90 },
    { label: '50 un', preco: 899.90 },
    { label: '100 un', preco: 1785.90 },
    { label: '200 un', preco: 3510.90 },
    { label: '500 un', preco: 8625.90 },
    { label: '1.000 un', preco: 17100.90 },
  ],
};

const bolsaHaste = {
  bg: 'linear-gradient(135deg,#fde68a,#d97706)', badge: 'Novo',
  imagem: 'img/bandeira.webp',
  nome: 'Bandeira',
  spec: 'Tecido gabardine · colorido só frente · sem verniz · 70x100 cm',
  variacoes: [
    { label: '1 un', preco: 89.90 },
  ],
};

const cordaoPersonalizado = {
  bg: 'linear-gradient(135deg,#fbcfe8,#9d174d)', badge: 'Novo',
  imagem: 'img/cordao.webp',
  nome: 'Cordão Personalizado',
  spec: 'Poliéster acetinado 20mm · colorido frente e verso · sem verniz · 39x2 cm · escolha o acabamento',
  variacoes: [
    { label: '10 un · Argola com Jacaré', preco: 174.90 },
    { label: '10 un · Mosquetão', preco: 198.90 },
    { label: '10 un · Argola com Jacaré Duplo', preco: 204.90 },
    { label: '10 un · Mosquetão Duplo', preco: 222.90 },
  ],
};

const FAIXAS_DRYFIT = [
  { label: '1 un', preco: 54.90 },
  { label: '5 un', preco: 268.90 },
  { label: '10 un', preco: 534.90 },
  { label: '20 un', preco: 1065.90 },
  { label: '30 un', preco: 1591.90 },
  { label: '40 un', preco: 2116.90 },
  { label: '50 un', preco: 2637.90 },
  { label: '100 un', preco: 5259.90 },
];
const camisetaDryMasc = {
  bg: 'linear-gradient(135deg,#e0f2fe,#0369a1)', badge: 'Novo',
  imagem: 'img/camiseta-masc.webp',
  imagens: ['img/camiseta-masc.webp', 'img/camiseta-masc-gola-brasil.webp', 'img/camiseta-masc-gola-v.webp', 'img/camiseta-masc-2.webp'],
  nome: 'Camiseta Dry Fit Masculina',
  arteRestrita: ARTE_SUBLIMACAO,
  distribuirTamanhos: true, unidade: 'camiseta', unidadePlural: 'camisetas',
  spec: 'Tipo Dry Fit · 100% poliéster · malha que absorve o suor · 3 golas (Brasil, redonda e V) · do P ao XL4',
  prazo: 7,
  paginaProduto: true,
  medidas: 'img/camiseta-masc-medidas.webp',
  descricao: 'Camiseta tipo Dry Fit — conforto e estilo em um único produto! Feita com uma malha especial que absorve o suor, mantendo você seco e confortável mesmo em dias quentes ou após uma atividade física. Importante: a malha é rústica e NÃO é elástica. Personalizável com a sua arte e com 3 opções de gola: Brasil, redonda e V.',
  detalhes: [
    'Composição: 100% poliéster com tecnologia Dry Fit.',
    'A malha é rústica e não é elástica (não estica).',
    'Vantagens: leve, respirável e durável, com propriedades que ajudam a controlar odores.',
    'Golas disponíveis: Brasil, redonda e V.',
    'Usos: uniformes de empresa, times esportivos, festas e eventos, identificação de equipes e funcionários, brindes de fim de ano e muito mais.',
    'Cuidados: lave em água fria, evite amaciante em excesso e não seque em altas temperaturas.',
  ],
  faq: [
    { p: 'O que é Dry Fit?', r: 'Um sistema de malha que absorve a umidade do corpo e evita que ela se acumule na pele, trazendo sensação de frescor e leveza mesmo em dias quentes ou após atividade física intensa.' },
    { p: 'Qual a composição da camisa?', r: 'É confeccionada em tecido 100% poliéster com tecnologia Dry Fit, deixando o usuário seco e confortável.' },
    { p: 'Quais são as vantagens do Dry Fit?', r: 'É leve, respirável e durável, e pode ter propriedades antimicrobianas que ajudam a controlar odores. Obs.: a malha é rústica e não é elástica.' },
    { p: 'Posso usar só para atividades físicas?', r: 'Não! Serve para uniformes de empresa, times esportivos, festas e eventos, identificação de equipes e funcionários, brindes de fim de ano e muito mais.' },
    { p: 'Como cuidar da camiseta?', r: 'Verifique as indicações de lavagem na etiqueta. Evite o uso intenso de amaciantes, lave em água fria e evite secar em altas temperaturas.' },
    { p: 'Posso personalizar do jeito que eu quiser?', r: 'Sim! É só nos enviar a sua arte ou nos contar a sua ideia que cuidamos de tudo, com a qualidade de sempre.' },
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  extra: { label: 'Gola', opcoes: ['Gola Brasil', 'Gola Redonda', 'Gola V'] },
  extraImagens: {
    'Gola Brasil': 'img/camiseta-masc-gola-brasil.webp',
    'Gola Redonda': 'img/camiseta-masc.webp',
    'Gola V': 'img/camiseta-masc-gola-v.webp',
  },
  tamanhos: {
    'P': FAIXAS_DRYFIT,
    'M': FAIXAS_DRYFIT,
    'G': FAIXAS_DRYFIT,
    'GG': FAIXAS_DRYFIT,
    'XL1': FAIXAS_DRYFIT,
    'XL2': FAIXAS_DRYFIT,
    'XL3': FAIXAS_DRYFIT,
    'XL4': FAIXAS_DRYFIT,
  },
};

const camisetaDryFem = {
  bg: 'linear-gradient(135deg,#e0f2fe,#0369a1)', badge: 'Novo',
  imagem: 'img/camiseta-fem.webp',
  nome: 'Camiseta Dry Fit Feminina',
  arteRestrita: ARTE_SUBLIMACAO,
  distribuirTamanhos: true, unidade: 'camiseta', unidadePlural: 'camisetas',
  spec: 'Tipo Dry Fit · 100% poliéster · malha que absorve o suor · golas redonda e V · do P ao XL4',
  prazo: 7,
  paginaProduto: true,
  medidas: 'img/camiseta-fem-medidas.webp',
  descricao: 'Camiseta feminina tipo Dry Fit — conforto e estilo em um único produto! Feita com uma malha especial que absorve o suor, mantendo você seca e confortável mesmo em dias quentes ou após uma atividade física. Personalizável com a sua arte e com 2 opções de gola: redonda e V.',
  detalhes: [
    'Composição: 100% poliéster com tecnologia Dry Fit.',
    'Vantagens: leve, respirável e de secagem rápida, com propriedades que ajudam a controlar odores.',
    'Golas disponíveis: redonda e V.',
    'Usos: uniformes de empresa, times esportivos, festas e eventos, identificação de equipes, brindes e muito mais.',
    'Cuidados: lave em água fria, evite amaciante em excesso e não seque em altas temperaturas.',
  ],
  faq: [
    { p: 'O que é Dry Fit?', r: 'Um sistema de malha que absorve a umidade do corpo e evita que ela se acumule na pele, trazendo sensação de frescor e leveza mesmo em dias quentes ou após atividade física intensa.' },
    { p: 'Qual a composição da camisa?', r: 'É confeccionada em tecido 100% poliéster com tecnologia Dry Fit, deixando a usuária seca e confortável.' },
    { p: 'Quais são as vantagens do Dry Fit?', r: 'É leve, respirável e de secagem rápida. Também pode ter propriedades que ajudam a controlar odores.' },
    { p: 'Como cuidar da camiseta?', r: 'Verifique as indicações de lavagem na etiqueta. Evite o uso intenso de amaciantes, lave em água fria e evite secar em altas temperaturas.' },
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  extra: { label: 'Gola', opcoes: ['Gola Redonda', 'Gola V'] },
  tamanhos: {
    'P': FAIXAS_DRYFIT,
    'M': FAIXAS_DRYFIT,
    'G': FAIXAS_DRYFIT,
    'GG': FAIXAS_DRYFIT,
    'XL1': FAIXAS_DRYFIT,
    'XL2': FAIXAS_DRYFIT,
    'XL3': FAIXAS_DRYFIT,
    'XL4': FAIXAS_DRYFIT,
  },
};

const camisaPesca = {
  bg: 'linear-gradient(135deg,#a5f3fc,#0e7490)', badge: 'Novo',
  imagem: 'img/camisa-pesca.webp',
  nome: 'Camisa de Pesca Personalizada',
  arteRestrita: ARTE_SUBLIMACAO,
  distribuirTamanhos: true, unidade: 'camisa', unidadePlural: 'camisas',
  spec: 'Manga longa · gola média com zíper · Active Ice UV 50+ · impressão Ultra HD Sublimática · do P ao XL4',
  prazo: 10,
  paginaProduto: true,
  medidas: 'img/camisa-pesca-medidas.webp',
  descricao: 'Você gosta de pescaria? Então chegou ao lugar certo! A Print House traz uma camisa de pesca personalizada para quem curte relaxar com estilo — ideal para aquele fim de semana, feriado prolongado ou férias, na hora sagrada de descansar e se concentrar. Personalização em impressão Ultra HD Sublimática, com cores nítidas e vibrantes.',
  detalhes: [
    'Modelo e caimento: camisa de manga longa, gola média e com zíper, com caimento confortável para os movimentos da pesca. Tamanhos do P ao XL4 (confira a tabela de medidas). Perfeita para pesca esportiva, amadora ou profissional, torneios e competições — e ótima como presente para quem ama pescar.',
    'Tecido: Active Ice UV 50+, resistente e refrescante, com conforto térmico, proteção UV 50+ e secagem ultra rápida. Ideal para nadar, remar e pescar com conforto.',
    'Áreas de personalização: frente, costas, braço direito, braço esquerdo, gola interna e gola externa. Obs.: a gola interna e externa deve ser personalizada com apenas 1 cor (chapada ou pattern), sem números, nomes ou desenhos, para não cortar a imagem.',
    'Cuidados: lave a peça separada das demais e não deixe de molho. Prefira a lavagem manual, seque no varal e à sombra, e não passe ferro nem seque a vapor — assim a camisa dura muito mais.',
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
          'P': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'M': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'G': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'GG': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'XL1': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'XL2': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'XL3': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
          'XL4': [
            { label: '1 un', preco: 121.90 },
            { label: '5 un', preco: 594.90 },
            { label: '10 un', preco: 1168.90 },
            { label: '20 un', preco: 2286.90 },
            { label: '30 un', preco: 3415.90 },
            { label: '40 un', preco: 4503.90 },
            { label: '50 un', preco: 5625.90 },
            { label: '100 un', preco: 10978.90 },
          ],
  },
};

const poloBordada = {
  bg: 'linear-gradient(135deg,#e2e8f0,#94a3b8)', badge: 'Novo',
  imagem: 'img/polo.webp',
  nome: 'Polo Bordada Personalizada',
  distribuirTamanhos: true, unidade: 'polo', unidadePlural: 'polos',
  spec: 'Bordado personalizado · do P ao GG',
  prazo: 7,
  paginaProduto: true,
  arteNota: 'Criação do layout do bordado no computador: R$ 60,00 (cobrado uma única vez por arte).',
  descricao: 'Camisa polo com bordado personalizado — a peça ideal para uniformes, empresas e equipes. O bordado dá um acabamento sofisticado e durável, que não desbota com as lavagens. Envie sua logo e nós criamos o layout do bordado no computador para aprovação antes da produção.',
  detalhes: [
    'Modelagem: camisa polo com gola e botões, tecido piquê de boa gramatura. Disponível do P ao GG.',
    'Personalização: bordado computadorizado a partir da sua logo ou referência. O layout do bordado é criado no computador (R$ 60,00 por arte) e enviado para sua aprovação.',
    'Prazo: 7 dias úteis após a aprovação da arte e confirmação do pagamento.',
  ],
  faq: [
    { p: 'O valor de R$ 60,00 do layout é cobrado por peça?', r: 'Não. A criação do layout do bordado no computador é cobrada uma única vez por arte, independente da quantidade de polos.' },
    { p: 'Preciso enviar a arte pronta?', r: 'Não. Basta enviar sua logo ou uma referência pelo WhatsApp que a nossa equipe cria o layout do bordado e envia a prévia para aprovação antes de produzir.' },
    { p: 'Como escolho os tamanhos?', r: 'Você distribui a quantidade por tamanho (do P ao GG) na hora do pedido. Some quantos quiser de cada tamanho.' },
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
    'P':  [{ label: '1 un', preco: 89.90 }],
    'M':  [{ label: '1 un', preco: 89.90 }],
    'G':  [{ label: '1 un', preco: 89.90 }],
    'GG': [{ label: '1 un', preco: 89.90 }],
  },
};

const moletomCanguru = {
  bg: 'linear-gradient(135deg,#cbd5e1,#334155)', badge: 'Novo',
  imagem: 'img/moletom.webp',
  nome: 'Moletom Canguru Personalizado',
  distribuirTamanhos: true, unidade: 'moletom', unidadePlural: 'moletons',
  spec: 'Moletom flanelado 100% poliéster · unissex · capuz e bolso canguru · impressão Ultra HD Sublimática · do P ao XL4',
  prazo: 10,
  paginaProduto: true,
  medidas: 'img/moletom-medidas.webp',
  descricao: 'Encontre o moletom canguru perfeito para o seu estilo! Conforto, elegância e personalidade em uma peça casual que combina com qualquer look. A Print House traz o moletom canguru personalizado com a sua estampa, em impressão Ultra HD Sublimática, com cores nítidas e vibrantes que não desbotam.',
  detalhes: [
    'O que é: o moletom canguru tem o clássico bolso costurado na frente, que acomoda as mãos e aquece com o tecido flanelado. Modelo com capuz, ideal para o friozinho do outono/inverno e para regiões mais frias.',
    'Tecido e modelagem: moletom flanelado 100% poliéster, quentinho e resistente. Unissex, do P ao XL4 (confira a tabela de medidas) — serve para vários portes e também para adolescentes.',
    'Áreas de personalização: frente, verso, manga direita, manga esquerda, capuz (partes 1 e 2), bolso e barras (1 a 4). Obs.: as barras (1 a 4) devem ser personalizadas com apenas 1 cor.',
    'Usos: perfeito para uniforme escolar, academia, caminhadas, eventos, shows e bandas — e ótimo de presente. Acabamento premium, com costuras bem-feitas e impressão que não desbota nem descostura com facilidade.',
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
          'P': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'M': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'G': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'GG': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'XL1': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'XL2': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'XL3': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
          'XL4': [
            { label: '1 un', preco: 135.90 },
            { label: '5 un', preco: 645.90 },
            { label: '10 un', preco: 1282.90 },
            { label: '20 un', preco: 2559.90 },
            { label: '30 un', preco: 3835.90 },
            { label: '40 un', preco: 5112.90 },
            { label: '50 un', preco: 6382.90 },
            { label: '100 un', preco: 12762.90 },
          ],
  },
};

const camisaAmericana = {
  bg: 'linear-gradient(135deg,#fde68a,#334155)', badge: 'Novo',
  imagem: 'img/camisa-americana.webp',
  nome: 'Camisa Futebol Americano Titan',
  arteRestrita: ARTE_SUBLIMACAO,
  distribuirTamanhos: true, unidade: 'camisa', unidadePlural: 'camisas',
  spec: 'Masculino · impressão Ultra HD Sublimática · do P ao XL4',
  prazo: 10,
  paginaProduto: true,
  medidas: 'img/camisa-americana-medidas.webp',
  descricao: 'Faça passes como um quarterback, receba como um wide receiver ou corra para o touchdown com a Camisa de Futebol Americano Titan! Uma peça leve, resistente e cheia de estilo para praticar, torcer ou colecionar, com personalização em impressão Ultra HD Sublimática.',
  detalhes: [
    'Modelagem: inspirada nas camisas oficiais, com recortes nos ombros e mangas largas e confortáveis. Modelagem maior, que veste com folga. Masculino, do P ao XL4 (confira a tabela de medidas).',
    'Tecido: tecido Favo de alta qualidade e durabilidade, que traz conforto, proteção e respiração para o corpo durante a partida.',
    'Personalização: total liberdade para criar sua camisa com nome, número e as cores do seu time — do jeito que você imaginar.',
  ],
  faq: [
          { p: 'Posso personalizar com nome e número?', r: 'Sim! Nome, número e cores são escolhidos na criação da sua camisa. Monte a que mais combina com você e sua equipe.' },
          { p: 'Como escolher o tamanho ideal?', r: 'Como a camisa tem recortes mais soltos, pode ficar mais larga conforme o tamanho. Use um casaco ou blusa maior como referência para comparar. Na dúvida, nossa equipe passa as medidas exatas no orçamento.' },
          { p: 'Como lavar e conservar?', r: 'Lave do avesso para proteger as costuras, com água fria e produtos suaves (evite cloro e alvejantes). Sabão comum de roupas já garante durabilidade e cor.' },
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
          'P': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'M': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'G': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'GG': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'XL1': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'XL2': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'XL3': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
          'XL4': [
            { label: '1 un', preco: 123.90 },
            { label: '5 un', preco: 607.90 },
            { label: '10 un', preco: 1200.90 },
            { label: '20 un', preco: 2368.90 },
            { label: '30 un', preco: 3505.90 },
            { label: '40 un', preco: 4612.90 },
            { label: '50 un', preco: 5689.90 },
            { label: '100 un', preco: 11224.90 },
          ],
  },
};

const camisaCiclismo = {
  bg: 'linear-gradient(135deg,#fde68a,#334155)', badge: 'Novo',
  imagem: 'img/camisa-ciclismo.webp',
  nome: 'Camisa de Ciclismo Fast',
  arteRestrita: ARTE_SUBLIMACAO,
  distribuirTamanhos: true, unidade: 'camisa', unidadePlural: 'camisas',
  spec: 'Masculino · impressão Ultra HD Sublimática · do P ao XL4',
  prazo: 10,
  paginaProduto: true,
  medidas: 'img/camisa-ciclismo-medidas.webp',
  descricao: 'Camisa de Ciclismo Fast com tecido leve e respirável, ideal para alta performance. Conforto, ajuste anatômico e acabamento premium — disponível em manga curta ou manga longa, com personalização em impressão Ultra HD Sublimática.',
  detalhes: [
    'Modelos: manga curta ou manga longa, com ajuste anatômico que acompanha o corpo. Masculino, do P ao XL4 (confira a tabela de medidas).',
    'Tecido: Active Ice UV 50+, leve, refrescante e com proteção UV 50+, secagem rápida e ótima respirabilidade para pedaladas longas.',
    'Personalização: crie a camisa do seu time, equipe ou marca com total liberdade de cores e artes.',
  ],
  extra: { label: 'Modelo', opcoes: ['Manga Curta', 'Manga Longa'] },
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
          'P': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'M': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'G': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'GG': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'XL1': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'XL2': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'XL3': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
          'XL4': [
            { label: '1 un', preco: 108.90 },
            { label: '5 un', preco: 537.90 },
            { label: '10 un', preco: 1072.90 },
            { label: '20 un', preco: 2140.90 },
            { label: '30 un', preco: 3207.90 },
            { label: '40 un', preco: 4269.90 },
            { label: '50 un', preco: 5328.90 },
            { label: '100 un', preco: 10639.90 },
          ],
  },
};

const jaquetaMisty = {
  bg: 'linear-gradient(135deg,#e2e8f0,#334155)', badge: 'Novo',
  nome: 'Jaqueta Corta Vento Misty',
  distribuirTamanhos: true, unidade: 'jaqueta', unidadePlural: 'jaquetas',
  spec: 'Tactel (92% poliéster · 8% elastano) · unissex · capuz e zíper 80 cm · do P ao XL4 · a partir de 1 un',
  imagem: 'img/jaqueta.webp',
  paginaProduto: true,
  prazo: 7,
  arteRestrita: true,
  medidas: 'img/jaqueta-medidas.webp',
  descricao: 'Buscando uma jaqueta para meia estação, que possa ser usada na academia, no pilates, no futebol de domingo ou em outros momentos do seu dia a dia? Você acabou de encontrar! Desenvolvida em tecido tactel (92% poliéster e 8% elastano) não respirável, a Jaqueta Corta Vento Misty da Print House é a opção perfeita para quem procura um casaco que proteja contra o vento e mantenha o corpo aquecido.',
  detalhes: ['A jaqueta leve corta vento tem zíper dentado jacaré de 80 cm e capuz, além de bolso frontal com forro, 8 recortes na frente, recorte em V nas costas e 3 recortes por manga. A costura é feita em máquina overloque, reta e à mão, garantindo um acabamento limpo, resistente e uniforme.', 'Uma jaqueta urbana corta vento da linha Premium, funcional para andar de moto, sair cedo pra academia ou fazer um cooper. Ideal para as mais variadas atividades físicas e do dia a dia, a Jaqueta Corta Vento Misty da Print House pode ser adquirida a partir de 1 unidade, do tamanho P ao XL4 — esse é o nosso grande diferencial. Fale com um dos nossos especialistas e faça seu orçamento!'],
  faq: [
          { p: 'A jaqueta é impermeável?', r: 'A jaqueta corta vento da Print House é feita em tactel (92% poliéster e 8% elastano), o que faz com que ela seque rápido e seja altamente resistente à água. Contudo, não é considerada totalmente impermeável.' },
          { p: 'Dá para usar o corta vento em dias frios?', r: 'Sim. É uma excelente opção para dias frios, sobretudo com vento, já que sua função é bloquear a brisa fria e evitar a perda de calor corporal.' },
          { p: 'O corta vento é indicado para corrida ou caminhada?', r: 'Sim, é super indicado para corrida ou caminhada, especialmente em dias ventosos ou frescos.' },
          { p: 'O tecido é respirável?', r: 'Não. A Jaqueta Misty não é respirável, devido à sua composição (92% poliéster e 8% elastano).' },
          { p: 'A modelagem é padrão ou slim?', r: 'A Jaqueta Corta Vento Misty tem modelagem padrão.' },
          { p: 'Como lavar a jaqueta?', r: 'Lave à mão ou no ciclo delicado com água fria e sabão líquido neutro. Feche os zíperes e vire do avesso, evitando amaciantes, alvejantes e secadora para preservar o tecido.' },
          { p: 'A jaqueta amassa fácil?', r: 'Não. O tactel é um material sintético conhecido pela praticidade e não amassa fácil.' },
          { p: 'Qual a diferença entre corta vento e jaqueta térmica?', r: 'O corta vento bloqueia o vento e é leve; a jaqueta térmica foca em reter o calor corporal para temperaturas baixas, sendo mais pesada e isolante.' },
          { p: 'A Misty é boa para viagens?', r: 'Sim. É leve, compacta e versátil, ideal para climas instáveis, atividades ao ar livre ou para usar sobre outras camadas em dias frios.' },
  ],
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  tamanhos: {
          'P': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'M': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'G': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'GG': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'XL1': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'XL2': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'XL3': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
          'XL4': [
            { label: '1 un', preco: 162.90 },
            { label: '5 un', preco: 799.90 },
            { label: '10 un', preco: 1584.90 },
            { label: '20 un', preco: 3136.90 },
            { label: '30 un', preco: 4659.90 },
            { label: '40 un', preco: 6150.90 },
            { label: '50 un', preco: 7611.90 },
            { label: '100 un', preco: 15067.90 },
          ],
  },
};

const canetaPersonalizada = {
  emoji: '🖊️', bg: 'linear-gradient(135deg,#fce7f3,#f472b6)',
  nome: 'Caneta Personalizada', spec: 'Gravação a laser 4x0 ou silk',
  variacoes: [
    { label: '100 un', preco: 119.90 },
    { label: '250 un', preco: 249.90 },
    { label: '500 un', preco: 419.90 },
  ],
};

/* Cores das sacolas plásticas com alça vazada (mesmas cores para todos os tamanhos) */
const CORES_SACOLA_PLASTICA = ['Amarelo', 'Azul', 'Azul Royal Transparente', 'Branco', 'Cobre', 'Laranja', 'Pink', 'Prata', 'Preto', 'Roxo', 'Transparente', 'Verde', 'Vermelho', 'Verde Tiffany'];

/* Chinelo personalizado — vai em Brindes (calçado/lembrancinha) */
const chineloPersonalizado = {
  bg: 'linear-gradient(135deg,#fbcfe8,#db2777)', badge: 'Novo', destaque: true,
  imagem: 'img/chinelo-personalizado.webp',
  nome: 'Chinelo Personalizado',
  spec: 'Borracha + EVA · impressão colorida só frente (4x0) · 26x34 cm · distribua a quantidade entre os tamanhos',
  unidade: 'chinelo', unidadePlural: 'chinelos',
  opcoesCombinacao: [
    { nome: 'Tam. 33/34', faixas: [{ min: 1, preco: 29.90 }] },
    { nome: 'Tam. 35/36', faixas: [{ min: 1, preco: 29.90 }] },
    { nome: 'Tam. 37/38', faixas: [{ min: 1, preco: 29.90 }] },
    { nome: 'Tam. 39/40', faixas: [{ min: 1, preco: 29.90 }] },
    { nome: 'Tam. 41/42', faixas: [{ min: 1, preco: 29.90 }] },
    { nome: 'Tam. 43/44', faixas: [{ min: 1, preco: 29.90 }] },
  ],
};

/* Forminhas para doces — aparece em Festas e em Embalagens */
const forminhasDoces = {
  bg: 'linear-gradient(135deg,#fde68a,#f59e0b)', badge: 'Novo', destaque: true,
  imagem: 'img/forminhas-doces.webp',
  nome: 'Forminhas para Doces (100 un)',
  spec: 'Forminhas personalizadas para doces · kit com 100 unidades · escolha o modelo',
  prazoTexto: 'de 2 a 5 dias úteis',
  variacoes: [
    { label: '100 un · Simples', preco: 29.90 },
    { label: '100 un · Em 3D', preco: 55.90 },
  ],
};

/* Caixinha Milk — aparece em Festas e em Embalagens */
const caixinhaMilk = {
  bg: 'linear-gradient(135deg,#fbcfe8,#c026d3)', badge: 'Novo', destaque: true,
  imagem: 'img/caixinha-milk.webp',
  imagens: ['img/caixinha-milk.webp', 'img/caixinha-milk-casamento.webp', 'img/caixinha-milk-dino.webp', 'img/caixinha-milk-super.webp'],
  nome: 'Caixinha Milk Personalizada',
  spec: 'Caixinha Milk personalizada · pedido mínimo 10 unidades · produção: 50 un em 5 dias úteis · 100 un em 8 dias úteis',
  prazoTexto: 'de 5 a 8 dias úteis',
  unidade: 'caixinha', unidadePlural: 'caixinhas',
  minimoTotal: 10,
  opcoesCombinacao: [
    { nome: 'Sem laço', faixas: [{ min: 1, preco: 4.50 }] },
    { nome: 'Com laço', faixas: [{ min: 1, preco: 5.00 }] },
  ],
};

/* Caixa de presente cartonada — aparece em Embalagens */
const caixaPresente = {
  bg: 'linear-gradient(135deg,#1f2937,#f59e0b)', badge: 'Novo', destaque: true,
  imagem: 'img/caixa-presente.webp',
  nome: 'Caixa de Presente Personalizada',
  spec: 'Caixa cartonada · acabamento vinil · logo ou escrita em dourado no topo · forro interno à sua escolha',
  prazoTexto: 'de 5 dias úteis',
  variacoes: [
    { label: 'Com laço', preco: 12.90 },
    { label: 'Toda preta com correntinha dourada', preco: 55.90 },
  ],
};

/* Sacolas — aparecem na categoria Sacolas e também em Embalagens */
const sacolaSilk = {
  bg: 'linear-gradient(135deg,#fbcfe8,#be185d)', badge: 'Novo', destaque: true,
  imagem: 'img/sacola-silk.webp',
  nome: 'Sacola em Papel Silk Premium',
  spec: 'Papel offset 150g · impressão silk 1 cor só frente · alça de gorgurão · escolha o tamanho, a cor da sacola, a cor da estampa e a quantidade',
  prazo: 20,
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  coresEstampa: ['Azul', 'Branco', 'Kraft/Dourado', 'Prata/Cinza', 'Rosa', 'Verde', 'Vermelho'],
  coresPorTamanho: {
    'P (15x8x14 cm)': ['Lilás', 'Creme', 'Branco', 'Preto', 'Azul'],
    'M (34x9x23 cm)': ['Creme', 'Azul', 'Branco', 'Preto'],
  },
  tamanhos: {
    'P (15x8x14 cm)': [
      { label: '10 un', preco: 274.90 },
      { label: '25 un', preco: 412.90 },
      { label: '50 un', preco: 645.90 },
      { label: '100 un', preco: 1105.90 },
    ],
    'M (34x9x23 cm)': [
      { label: '10 un', preco: 361.90 },
      { label: '25 un', preco: 603.90 },
      { label: '50 un', preco: 1077.90 },
      { label: '100 un', preco: 1939.90 },
    ],
  },
};
const sacolaPlastica = {
  bg: 'linear-gradient(135deg,#bfdbfe,#1d4ed8)', badge: 'Novo', destaque: true,
  imagem: 'img/sacola-plastica.webp',
  nome: 'Sacola Plástica com Alça Vazada',
  spec: 'Plástico resistente · alça vazada · impressão personalizada · escolha o tamanho, a cor da sacola, a cor da impressão e a quantidade',
  prazoTexto: 'de 3 a 7 dias úteis',
  grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
  coresEstampa: ['Azul Claro', 'Branco', 'Dourado', 'Cinza', 'Preto', 'Rosa Pink', 'Verde', 'Vermelho'],
  coresPorTamanho: {
    'P': CORES_SACOLA_PLASTICA,
    'M': CORES_SACOLA_PLASTICA,
    'G': CORES_SACOLA_PLASTICA,
  },
  tamanhos: {
    'P': [
      { label: '50 un', preco: 192.90 },
      { label: '100 un', preco: 237.90 },
      { label: '250 un', preco: 379.90 },
      { label: '500 un', preco: 613.90 },
      { label: '1.000 un', preco: 1110.90 },
    ],
    'M': [
      { label: '50 un', preco: 210.90 },
      { label: '100 un', preco: 283.90 },
      { label: '250 un', preco: 508.90 },
      { label: '500 un', preco: 880.90 },
      { label: '1.000 un', preco: 1645.90 },
    ],
    'G': [
      { label: '50 un', preco: 294.90 },
      { label: '100 un', preco: 433.90 },
      { label: '250 un', preco: 885.90 },
      { label: '500 un', preco: 1645.90 },
      { label: '1.000 un', preco: 3258.90 },
    ],
  },
};
const sacolaCordao = {
  bg: 'linear-gradient(135deg,#fef3c7,#b45309)', badge: 'Novo', destaque: true,
  imagem: 'img/sacola-alca-cordao.webp',
  nome: 'Sacola de Papel com Alça de Cordão',
  spec: 'Papel · 29 x 25 x 8 cm · alça de cordão · pedido mínimo 10 unidades. A sacola não é colorida: apenas a logo da frente é impressa em cor e as laterais recebem um padrão (pattern) da sua logo — sem cores chapadas.',
  unidade: 'sacola', unidadePlural: 'sacolas',
  minimoTotal: 10,
  opcoesCombinacao: [
    { nome: 'Alça de cordão padrão', faixas: [{ min: 1, preco: 9.00 }] },
    { nome: 'Alça na cor da sua identidade visual', faixas: [{ min: 1, preco: 10.00 }] },
  ],
};

const CATALOGO = {
  'kits': {
    nome: 'Kits',
    emoji: '🎁',
    banner: 'linear-gradient(120deg,#7c3aed,#db2777)',
    descricao: 'Kits personalizados prontos para presentear, divulgar sua marca ou compor brindes corporativos.',
    produtos: [
      { bg: 'linear-gradient(135deg,#ede9fe,#7c3aed)', badge: 'Novo', destaque: true,
        imagem: 'img/kit-basico-3.webp',
        nome: 'Kit All Black – 3 Itens',
        spec: '01 sacola P (papel offset fosco 180g · ~19x15x6 cm) + 01 bloquinho de anotações P (capa dura · 8x11 cm) + 01 caneta Slim Touch personalizada com gravação a laser · Consultar as cores das canetas e dos copos.',
        variacoes: [
          { label: 'Kit completo', preco: 55.90 },
        ] },
      { bg: 'linear-gradient(135deg,#fce7f3,#db2777)', badge: 'Novo', destaque: true,
        imagem: 'img/kit-basico-plus.webp',
        nome: 'Kit Básico Plus – 4 Itens',
        spec: '01 sacola P (papel offset fosco 180g · ~19x15x6 cm) + 01 bloquinho de anotações P (capa dura · 8x11 cm) + 01 caneta Slim Touch personalizada com gravação a laser + 01 certificado (papel fosco 180g) · Consultar as cores das canetas e dos copos.',
        arteNota: 'A arte do certificado é enviada pelo cliente.',
        variacoes: [
          { label: 'Com laço', preco: 65.00 },
          { label: 'Sem laço', preco: 65.00 },
        ] },
      { bg: 'linear-gradient(135deg,#fef9c3,#ca8a04)', badge: 'Novo', destaque: true,
        imagem: 'img/kit-luxo.webp',
        nome: 'Kit Luxo – 4 Itens',
        spec: '01 sacola personalizada M (papel offset fosco 180g · ~24x17x10 cm) + 01 bloquinho de anotações P (capa dura · 8x11 cm) + 01 caneta Slim Touch com gravação a laser + 01 taça de gin (com ou sem laço) · Consultar as cores das canetas e dos copos.',
        variacoes: [
          { label: 'All Black', preco: 145.00 },
          { label: 'Colorido', preco: 135.00 },
        ] },
    ],
  },

  'sacolas': {
    nome: 'Sacolas',
    emoji: '🛍️',
    banner: 'linear-gradient(120deg,#9d174d,#f472b6)',
    descricao: 'Sacolas de papel personalizadas para valorizar a entrega da sua marca.',
    produtos: [
      sacolaSilk,
      sacolaPlastica,
      sacolaCordao,
    ],
  },

  'apostilas': {
    nome: 'Apostilas',
    emoji: '📚',
    banner: 'linear-gradient(120deg,#1e3a8a,#3b82f6)',
    descricao: 'Apostilas e materiais didáticos personalizados para cursos, treinamentos e escolas.',
    produtos: [
      { bg: 'linear-gradient(135deg,#dbeafe,#1d4ed8)', badge: 'Novo', destaque: true,
        imagem: 'img/apostila.webp',
        nome: 'Apostila Personalizada',
        spec: 'Monte a sua apostila folha a folha: escolha o tipo de folha, a quantidade e some capa e contra capa se quiser',
        prazoTexto: 'de 1 a 3 dias úteis',
        arteNota: 'Criação da arte da apostila: R$ 65,00.',
        unidade: 'folha', unidadePlural: 'folhas',
        adicional: { label: 'Capa e Contra Capa', preco: 10.00 },
        opcoesCombinacao: [
          { nome: 'Folha Preta — Matte 170g', faixas: [{ min: 1, preco: 2.00 }] },
          { nome: 'Folha Colorida — Sulfite 75g', faixas: [{ min: 1, preco: 1.50 }] },
          { nome: 'Folha Preto e Branco — Sulfite 75g', faixas: [{ min: 1, preco: 1.00 }] },
        ] },
    ],
  },

  'impressao-rapida': {
    nome: 'Impressão Rápida',
    emoji: '🖨️',
    banner: 'linear-gradient(120deg,#0f766e,#14b8a6)',
    descricao: 'Impressão em jato de tinta na hora: escolha o papel e a cor, conte quantas folhas quiser e pronto.',
    produtos: [
      { bg: 'linear-gradient(135deg,#ccfbf1,#0d9488)', badge: 'Novo', destaque: true,
        nome: 'Impressão Rápida (por folha)',
        spec: 'Impressão em jato de tinta · escolha o papel e a cor e some quantas folhas quiser',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'folha', unidadePlural: 'folhas',
        opcoesCombinacao: [
          { nome: 'Sulfite 75g · Preto e Branco', faixas: [{ min: 1, preco: 0.50 }] },
          { nome: 'Sulfite 75g · Colorido', faixas: [{ min: 1, preco: 1.00 }] },
          { nome: 'Sulfite 90g · Colorido', faixas: [{ min: 1, preco: 1.50 }] },
          { nome: 'Papel Matte Fosco 180g · Preto e Branco', faixas: [{ min: 1, preco: 3.00 }] },
          { nome: 'Papel Matte Fosco 180g · Colorido', faixas: [{ min: 1, preco: 3.50 }] },
          { nome: 'Papel Glossy 250g · Preto e Branco', faixas: [{ min: 1, preco: 3.00 }] },
          { nome: 'Papel Glossy 250g · Colorido', faixas: [{ min: 1, preco: 3.50 }] },
        ] },
    ],
  },

  'grafica-rapida': {
    nome: 'Gráfica Rápida (Balcão)',
    emoji: '⚡',
    banner: 'linear-gradient(120deg,#b45309,#f59e0b)',
    descricao: 'Serviços de balcão do dia a dia: escolha aqui, envie o arquivo pelo WhatsApp e retire na loja ou receba por motoboy/Uber.',
    produtos: [
      { bg: 'linear-gradient(135deg,#fef3c7,#b45309)', badge: 'Novo', destaque: true,
        nome: 'Cópias / Xerox (por folha)',
        spec: 'Cópia P&B ou colorida · A4 · escolha a cor e some quantas folhas quiser',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'folha', unidadePlural: 'folhas',
        semArte: 'Traga o documento na loja, ou envie o arquivo (PDF/foto) pelo <strong>WhatsApp</strong> ou e-mail que imprimimos para você.',
        opcoesCombinacao: [
          { nome: 'Preto e Branco', faixas: [{ min: 1, preco: 0.50 }, { min: 10, preco: 0.40 }, { min: 50, preco: 0.30 }, { min: 100, preco: 0.25 }] },
          { nome: 'Colorida', faixas: [{ min: 1, preco: 2.00 }, { min: 10, preco: 1.50 }, { min: 50, preco: 1.20 }, { min: 100, preco: 1.00 }] },
        ] },
      { bg: 'linear-gradient(135deg,#e0f2fe,#0369a1)', badge: 'Novo', destaque: true,
        nome: 'Impressão de Documentos (por página)',
        spec: 'Envie o PDF pelo WhatsApp ou e-mail · impressão P&B ou colorida · A4 · retire na loja ou receba por motoboy/Uber',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'página', unidadePlural: 'páginas',
        semArte: 'Envie o seu documento em <strong>PDF</strong> pelo <strong>WhatsApp</strong> ou e-mail — imprimimos e você retira na loja ou recebe por motoboy/Uber.',
        opcoesCombinacao: [
          { nome: 'Preto e Branco · Só frente', faixas: [{ min: 1, preco: 0.50 }, { min: 50, preco: 0.35 }, { min: 100, preco: 0.25 }] },
          { nome: 'Preto e Branco · Frente e verso', faixas: [{ min: 1, preco: 0.80 }, { min: 50, preco: 0.60 }, { min: 100, preco: 0.45 }] },
          { nome: 'Colorida · Só frente', faixas: [{ min: 1, preco: 2.00 }, { min: 50, preco: 1.20 }, { min: 100, preco: 1.00 }] },
        ] },
      { bg: 'linear-gradient(135deg,#ede9fe,#6d28d9)', badge: 'Novo', destaque: true,
        nome: 'Digitalização / Escaneamento (por página)',
        spec: 'Escaneamos seus documentos e enviamos em PDF por WhatsApp ou e-mail',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'página', unidadePlural: 'páginas',
        semArte: 'Traga os documentos na loja. Devolvemos o arquivo digitalizado em <strong>PDF</strong> pelo WhatsApp ou e-mail.',
        opcoesCombinacao: [
          { nome: 'Digitalização em PDF', faixas: [{ min: 1, preco: 1.00 }, { min: 20, preco: 0.70 }, { min: 50, preco: 0.50 }] },
        ] },
      { bg: 'linear-gradient(135deg,#dcfce7,#15803d)', badge: 'Novo', destaque: true,
        nome: 'Plastificação',
        spec: 'Plastificação (laminação) de documentos e cartões · escolha o tamanho',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'plastificação', unidadePlural: 'plastificações',
        semArte: 'Traga o documento na loja ou envie o arquivo pelo <strong>WhatsApp</strong> para imprimirmos e plastificarmos.',
        grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
        variacoes: [
          { label: 'Crachá / Cartão', preco: 3.00 },
          { label: 'A4', preco: 6.00 },
          { label: 'A3', preco: 12.00 },
        ] },
      { bg: 'linear-gradient(135deg,#fce7f3,#be185d)', badge: 'Novo', destaque: true,
        nome: 'Encadernação',
        spec: 'Espiral ou capa dura · escolha pelo número de folhas',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'encadernação', unidadePlural: 'encadernações',
        semArte: 'Traga o material impresso ou envie o arquivo pelo <strong>WhatsApp</strong> — imprimimos e encadernamos para você.',
        opcoesCombinacao: [
          { nome: 'Espiral · até 50 folhas', faixas: [{ min: 1, preco: 6.00 }] },
          { nome: 'Espiral · até 100 folhas', faixas: [{ min: 1, preco: 9.00 }] },
          { nome: 'Espiral · até 200 folhas', faixas: [{ min: 1, preco: 14.00 }] },
          { nome: 'Capa dura (a partir de)', faixas: [{ min: 1, preco: 45.00 }] },
        ] },
      { bg: 'linear-gradient(135deg,#fee2e2,#b91c1c)', badge: 'Novo', destaque: true,
        nome: 'Impressão de Fotos',
        spec: 'Impressão de fotos e documentos · escolha o tamanho',
        prazoTexto: 'na hora / no mesmo dia',
        unidade: 'foto', unidadePlural: 'fotos',
        semArte: 'Envie as fotos pelo <strong>WhatsApp</strong> ou traga na loja (pen drive/celular). Retire na loja ou receba por motoboy/Uber.',
        grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
        variacoes: [
          { label: 'Foto 3x4 (cartela com 6)', preco: 10.00 },
          { label: 'Foto 5x7', preco: 5.00 },
          { label: 'Foto 10x15', preco: 3.00 },
          { label: 'Foto 15x21', preco: 6.00 },
          { label: 'Pôster A3', preco: 20.00 },
        ] },
    ],
  },

  'papelaria': {
    nome: 'Papelaria',
    emoji: '📓',
    banner: 'linear-gradient(120deg,#4338ca,#818cf8)',
    descricao: 'Cadernos, blocos e itens de papelaria personalizados para a sua marca.',
    produtos: [
      { bg: 'linear-gradient(135deg,#e0e7ff,#4338ca)', badge: 'Novo', destaque: true,
        nome: 'Caderninho 7x10 cm',
        spec: 'Capa personalizada (só a capa) · 64 folhas · 7x10 cm · Mais quantidades: consultar valor no atacado.',
        variacoes: [
          { label: '1 un', preco: 12.90 },
        ] },
    ],
  },

  'comunicacao-visual': {
    nome: 'Comunicação Visual',
    emoji: '🖥️',
    banner: 'linear-gradient(120deg,#0f172a,#334155)',
    descricao: 'Soluções de comunicação visual para valorizar sua marca em pontos de venda, eventos e ambientes comerciais.',
    produtos: [
      { bg: 'linear-gradient(135deg,#e2e8f0,#334155)', badge: 'Novo', destaque: true,
        paginaProduto: true,
        semArte: true,
        imagem: 'img/quadro-iluminado.webp',
        nome: 'Quadro Iluminado LED Branco 310x425mm',
        spec: 'Estrutura de alumínio, vidro e LED branco · 310x425mm aprox. · produto sem personalização',
        descricao: 'O quadro com LED branco é ideal para quem busca uma solução moderna e elegante para destacar informações, imagens e campanhas. A iluminação uniforme valoriza a comunicação visual e cria maior destaque em ambientes comerciais, eventos e pontos de venda. Prático e versátil, pode ser utilizado com folhas personalizadas vendidas separadamente, permitindo atualizar a mensagem sempre que necessário. Invista em um quadro iluminado para valorizar sua marca.',
        detalhes: [
          'Matéria-prima: alumínio, vidro e LED branco.',
          'Tamanho final aproximado: 310x425mm.',
          'Tipo de impressão: produto sem personalização.',
          'Não acompanha a folha personalizada (vendida separadamente).',
          'Fonte Bivolt inclusa — deve ficar conectada diretamente na energia.',
        ],
        variacoes: [
          { label: '1 un', preco: 350.00 },
        ] },
    ],
  },

  'servicos-digitais': {
    nome: 'Serviços Digitais',
    emoji: '💻',
    banner: 'linear-gradient(120deg,#4c1d95,#7c3aed)',
    descricao: 'Criação de materiais digitais pela nossa equipe, entregues em arquivo — sem impressão.',
    produtos: [
      { bg: 'linear-gradient(135deg,#ede9fe,#6d28d9)', badge: 'Novo', destaque: true,
        imagem: 'img/servico-design.webp',
        nome: 'Elaboração de Apostila ou Catálogo',
        spec: 'Criação da arte pela nossa equipe · entregue em PDF de alta resolução · escolha o número de páginas',
        semArte: 'Serviço de criação: nossa equipe elabora a sua apostila ou catálogo. Após a compra, envie o conteúdo (textos e imagens) pelo WhatsApp. Entregamos o arquivo final em <strong>PDF de alta resolução</strong>.',
        variacoes: [
          { label: 'Até 15 páginas', preco: 120.00 },
          { label: 'Até 20 páginas', preco: 145.00 },
        ] },
      { bg: 'linear-gradient(135deg,#c7d2fe,#4338ca)', badge: 'Promoção', destaque: true,
        nome: 'Mini Site (até 50 itens)',
        spec: 'Mini site profissional com até 50 itens · de R$ 480,00 por R$ 250,00 na promoção',
        semArte: 'Mini site profissional com até 50 itens. Valor promocional de R$ 250,00 (normalmente R$ 480,00). O <strong>domínio (endereço do site) fica por conta do cliente</strong> — valores a partir de R$ 11,00 (consultar com a gráfica). Após a compra, envie o seu conteúdo (textos, imagens e itens) pelo WhatsApp.',
        variacoes: [
          { label: 'Até 50 itens (promoção)', preco: 250.00 },
        ] },
    ],
  },

  'festas': {
    nome: 'Festas',
    emoji: '🎉',
    banner: 'linear-gradient(120deg,#be123c,#fb7185)',
    descricao: 'Topos de bolo e itens personalizados para deixar a sua festa com a sua cara.',
    produtos: [
      { bg: 'linear-gradient(135deg,#fbcfe8,#db2777)', badge: 'Novo', destaque: true,
        imagem: 'img/topo-bolo.webp',
        nome: 'Topo de Bolo Personalizado',
        spec: 'Recorte em lamicote com canudo transparente · folha 21x39 cm (recorte o que quiser) · escolha o modelo',
        prazoTexto: 'de 1 a 5 dias úteis',
        variacoes: [
          { label: 'Simples (recorte em lamicote)', preco: 15.90 },
          { label: 'Em 3D com fundo', preco: 25.90 },
          { label: 'Elaborado com várias peças de um tema', preco: 49.90 },
          { label: 'Elaborado em 3D', preco: 55.90 },
        ] },
      forminhasDoces,
      caixinhaMilk,
    ],
  },

  'cartoes-de-visita': {
    nome: 'Cartões de Visita',
    emoji: '💼',
    banner: 'linear-gradient(120deg,#b45309,#f59e0b)',
    descricao: 'Cause uma ótima primeira impressão com cartões de alta qualidade.',
    produtos: [
      { bg: 'linear-gradient(135deg,#fef08a,#ca8a04)', badge: 'Novo', prazo: 3, destaque: true,
        imagem: 'img/cartao-visita.webp',
        nome: 'Cartão de Visita Couchê 250g',
        spec: 'Couchê 250g · UV total frente · 8,8x4,8 cm · escolha a cor e a quantidade',
        grupoLabel: 'Cor', opcaoLabel: 'Quantidade',
        tamanhos: {
          'Colorido só frente': [
            { label: '500 un', preco: 70.90 },
            { label: '1.000 un', preco: 99.90 },
            { label: '3.000 un', preco: 286.90 },
            { label: '5.000 un', preco: 459.90 },
            { label: '10.000 un', preco: 909.90 },
          ],
          'Colorido frente e verso': [
            { label: '500 un', preco: 100.90 },
            { label: '1.000 un', preco: 125.00 },
            { label: '3.000 un', preco: 336.90 },
            { label: '5.000 un', preco: 546.90 },
            { label: '10.000 un', preco: 1090.90 },
          ],
          'Frente colorida + verso P&B': [
            { label: '500 un', preco: 75.90 },
            { label: '1.000 un', preco: 106.90 },
            { label: '3.000 un', preco: 304.90 },
            { label: '5.000 un', preco: 478.90 },
            { label: '10.000 un', preco: 955.90 },
          ],
        } },
      { bg: 'linear-gradient(135deg,#fbcfe8,#be185d)', badge: 'Novo',
        imagem: 'img/postal.webp',
        nome: 'Postal Couchê 250g',
        spec: 'Couchê 250g · UV total frente · 8,8x9,94 cm · escolha a cor e a quantidade',
        grupoLabel: 'Cor', opcaoLabel: 'Quantidade',
        tamanhos: {
          'Colorido só frente': [
            { label: '100 un', preco: 76.90 },
            { label: '250 un', preco: 84.90 },
            { label: '500 un', preco: 106.90 },
            { label: '1.000 un', preco: 181.90 },
          ],
          'Colorido frente e verso': [
            { label: '100 un', preco: 90.90 },
            { label: '250 un', preco: 96.90 },
            { label: '500 un', preco: 133.90 },
            { label: '1.000 un', preco: 217.90 },
          ],
        } },
      { bg: 'linear-gradient(135deg,#ddd6fe,#6d28d9)', badge: 'Novo',
        imagem: 'img/solapa.webp',
        nome: 'Solapa para Embalagem',
        spec: 'Cabeçalho de embalagem (solapa) · colorido só frente · escolha o tamanho e a quantidade',
        tamanhos: {
          'Tamanho padrão': [
            { label: '50 un', preco: 44.90 },
            { label: '100 un', preco: 82.90 },
            { label: '250 un', preco: 187.90 },
            { label: '500 un', preco: 243.90 },
            { label: '1.000 un', preco: 294.90 },
            { label: '3.000 un', preco: 822.90 },
            { label: '5.000 un', preco: 1258.90 },
          ],
          '17,9 x 9,94 cm': [
            { label: '50 un', preco: 82.90 },
            { label: '100 un', preco: 157.90 },
            { label: '250 un', preco: 367.90 },
            { label: '500 un', preco: 484.90 },
            { label: '1.000 un', preco: 588.90 },
            { label: '3.000 un', preco: 1621.90 },
            { label: '5.000 un', preco: 2511.90 },
          ],
          '18 x 20 cm': [
            { label: '50 un', preco: 159.90 },
            { label: '100 un', preco: 298.90 },
            { label: '250 un', preco: 698.90 },
            { label: '500 un', preco: 931.90 },
            { label: '1.000 un', preco: 1137.90 },
          ],
        } },
      { bg: 'linear-gradient(135deg,#e2e8f0,#475569)', badge: 'Novo', destaque: true,
        paginaProduto: true,
        imagem: 'img/cartao-dois-cantos.webp',
        nome: 'Cartão de Visita Dois Cantos Arredondados 300g',
        spec: 'Couchê 300g · laminação fosca · dois cantos arredondados · 8,8 × 5,08 cm · escolha a impressão e a quantidade',
        prazoTexto: 'de 3 a 5 dias úteis',
        grupoLabel: 'Impressão', opcaoLabel: 'Quantidade',
        furos: [
          { ate: 1000, preco: 30.00 },
          { ate: 2500, preco: 50.00 },
          { ate: 5000, preco: 80.00 },
        ],
        tamanhos: {
          'Colorido frente e verso (4x4)': [
            { label: '500 un', preco: 211.90 },
            { label: '1.000 un', preco: 289.90 },
            { label: '3.000 un', preco: 783.90 },
          ],
          'Colorido só frente': [
            { label: '500 un', preco: 204.90 },
            { label: '1.000 un', preco: 273.90 },
            { label: '3.000 un', preco: 727.90 },
            { label: '5.000 un', preco: 1211.90 },
          ],
        },
        descricao: 'Cartão de visita com dois cantos arredondados, em Couchê 300g com laminação fosca. Elegante, resistente e com toque suave — ótimo também como tag, com opção de furo para cordão.',
        detalhes: [
          'Categoria: Dois Cantos Arredondados',
          'Material: Couchê 300g',
          'Impressão: 4x4 (frente e verso coloridos) ou colorido só frente',
          'Cobertura: Laminação Fosca',
          'Tamanho: 8,8 × 5,08 cm',
          'Acabamento Incluso: Dois Cantos Arredondados',
          'Furo opcional para tags: até 1.000 un R$ 30,00 · até 2.500 un R$ 50,00 · até 5.000 un R$ 80,00.',
        ] },
    ],
  },

  'panfletos': {
    nome: 'Panfletos',
    emoji: '📄',
    banner: 'linear-gradient(120deg,#1e40af,#3b82f6)',
    descricao: 'Flyers em couchê 80g para divulgar promoções e serviços — escolha o tamanho, a cor e a quantidade.',
    produtos: [
      { bg: 'linear-gradient(135deg,#bfdbfe,#2563eb)', badge: 'Novo', destaque: true,
        imagem: 'img/flyer.webp',
        nome: 'Flyer Couchê 80g',
        spec: 'Couchê 80g · sem verniz · escolha o tamanho, a cor e a quantidade',
        /* Produto com tamanhos: o cliente escolhe o tamanho e a opção em dropdowns */
        tamanhos: {
          '7x10 cm': [
            { label: '2.000 un · Colorido só frente', preco: 208.90 },
            { label: '5.000 un · Colorido só frente', preco: 297.90 },
            { label: '10.000 un · Colorido só frente', preco: 478.90 },
            { label: '2.000 un · Colorido frente e verso', preco: 237.90 },
            { label: '5.000 un · Colorido frente e verso', preco: 358.90 },
            { label: '10.000 un · Colorido frente e verso', preco: 493.90 },
          ],
          '14x10 cm': [
            { label: '1.000 un · Colorido só frente', preco: 139.90 },
            { label: '2.500 un · Colorido só frente', preco: 283.90 },
            { label: '5.000 un · Colorido só frente', preco: 382.90 },
            { label: '10.000 un · Colorido só frente', preco: 712.90 },
            { label: '2.500 un · Colorido frente e verso', preco: 310.90 },
            { label: '5.000 un · Colorido frente e verso', preco: 561.90 },
            { label: '10.000 un · Colorido frente e verso', preco: 1062.90 },
          ],
          '14x20 cm': [
            { label: '1.000 un · Colorido só frente', preco: 270.90 },
            { label: '2.500 un · Colorido só frente', preco: 492.90 },
            { label: '5.000 un · Colorido só frente', preco: 745.90 },
            { label: '10.000 un · Colorido só frente', preco: 1474.90 },
            { label: '1.000 un · Colorido frente e verso', preco: 330.90 },
            { label: '2.500 un · Colorido frente e verso', preco: 592.90 },
            { label: '5.000 un · Colorido frente e verso', preco: 874.90 },
            { label: '10.000 un · Colorido frente e verso', preco: 1698.90 },
          ],
          '15x10 cm': [
            { label: '1.000 un · Colorido só frente', preco: 148.90 },
            { label: '2.500 un · Colorido só frente', preco: 337.90 },
            { label: '5.000 un · Colorido só frente', preco: 519.90 },
            { label: '10.000 un · Colorido só frente', preco: 961.90 },
            { label: '1.000 un · Colorido frente e verso', preco: 183.90 },
            { label: '2.500 un · Colorido frente e verso', preco: 349.90 },
            { label: '5.000 un · Colorido frente e verso', preco: 571.90 },
            { label: '10.000 un · Colorido frente e verso', preco: 1081.90 },
          ],
          '15x21 cm': [
            { label: '1.000 un · Colorido só frente', preco: 277.90 },
            { label: '2.500 un · Colorido só frente', preco: 501.90 },
            { label: '5.000 un · Colorido só frente', preco: 781.90 },
            { label: '10.000 un · Colorido só frente', preco: 1534.90 },
            { label: '1.000 un · Colorido frente e verso', preco: 339.90 },
            { label: '2.500 un · Colorido frente e verso', preco: 601.90 },
            { label: '5.000 un · Colorido frente e verso', preco: 897.90 },
            { label: '10.000 un · Colorido frente e verso', preco: 1756.90 },
          ],
          '20x21 cm': [
            { label: '1.000 un · Colorido só frente', preco: 417.90 },
            { label: '2.500 un · Colorido só frente', preco: 774.90 },
            { label: '5.000 un · Colorido só frente', preco: 1414.90 },
            { label: '10.000 un · Colorido só frente', preco: 2826.90 },
            { label: '1.000 un · Colorido frente e verso', preco: 511.90 },
            { label: '2.500 un · Colorido frente e verso', preco: 892.90 },
            { label: '5.000 un · Colorido frente e verso', preco: 1615.90 },
            { label: '10.000 un · Colorido frente e verso', preco: 3228.90 },
          ],
        } },
    ],
  },

  'adesivos': {
    nome: 'Adesivos',
    emoji: '🏷️',
    banner: 'linear-gradient(120deg,#15803d,#22c55e)',
    descricao: 'Adesivos e rótulos em vinil resistente, com recorte no formato que você quiser.',
    produtos: [
      { bg: 'linear-gradient(135deg,#bbf7d0,#22c55e)', badge: 'Novo', destaque: true,
        imagem: 'img/adesivos.webp',
        nome: 'Adesivos Personalizados',
        spec: 'Redondos e quadrados · impressão colorida em alta qualidade · corte especial · escolha o tamanho e a quantidade',
        grupoLabel: 'Tamanho', opcaoLabel: 'Quantidade',
        tamanhos: {
          '2×2 cm': [
            { label: '50 un', preco: 40.00 },
            { label: '100 un', preco: 45.00 },
            { label: '250 un', preco: 50.00 },
            { label: '500 un', preco: 58.00 },
            { label: '1.000 un', preco: 100.00 },
          ],
          '3×3 cm': [
            { label: '50 un', preco: 40.00 },
            { label: '100 un', preco: 45.00 },
            { label: '250 un', preco: 120.00 },
            { label: '500 un', preco: 160.00 },
            { label: '1.000 un', preco: 166.00 },
          ],
          '4×4 cm': [
            { label: '50 un', preco: 40.00 },
            { label: '100 un', preco: 58.00 },
            { label: '250 un', preco: 133.00 },
            { label: '500 un', preco: 150.00 },
            { label: '1.000 un', preco: 180.00 },
          ],
          '5×5 cm': [
            { label: '50 un', preco: 55.00 },
            { label: '100 un', preco: 60.00 },
            { label: '250 un', preco: 120.00 },
            { label: '500 un', preco: 130.00 },
            { label: '1.000 un', preco: 230.00 },
          ],
          '6×6 cm': [
            { label: '50 un', preco: 60.00 },
            { label: '100 un', preco: 65.00 },
            { label: '250 un', preco: 117.00 },
            { label: '500 un', preco: 170.00 },
            { label: '1.000 un', preco: 285.00 },
          ],
          '7×7 cm': [
            { label: '50 un', preco: 62.00 },
            { label: '100 un', preco: 68.00 },
            { label: '250 un', preco: 120.00 },
            { label: '500 un', preco: 230.00 },
            { label: '1.000 un', preco: 390.00 },
          ],
          '8×8 cm': [
            { label: '50 un', preco: 60.00 },
            { label: '100 un', preco: 80.00 },
            { label: '250 un', preco: 178.00 },
            { label: '500 un', preco: 280.00 },
            { label: '1.000 un', preco: 520.00 },
          ],
          '9×9 cm': [
            { label: '50 un', preco: 65.00 },
            { label: '100 un', preco: 98.00 },
            { label: '250 un', preco: 110.00 },
            { label: '500 un', preco: 340.00 },
            { label: '1.000 un', preco: 620.00 },
          ],
          '10×10 cm': [
            { label: '50 un', preco: 60.00 },
            { label: '100 un', preco: 115.00 },
            { label: '250 un', preco: 220.00 },
            { label: '500 un', preco: 365.00 },
            { label: '1.000 un', preco: 910.00 },
          ],
          'Medida personalizada': [
            { label: 'A combinar', preco: null },
          ],
        } },
      { bg: 'linear-gradient(135deg,#d9f99d,#65a30d)', badge: 'Novo', destaque: true,
        paginaProduto: true,
        nome: 'Adesivo DTF UV',
        spec: 'Adesivo em DTF UV · alta definição, brilho e acabamento premium · escolha o tamanho',
        prazoTexto: 'de 2 a 3 dias úteis',
        descricao: 'Adesivo personalizado produzido com tecnologia DTF UV, que oferece alta definição, brilho e acabamento premium. Ideal para brindes, embalagens, copos, papelaria criativa e diversos produtos personalizados.',
        variacoes: [
          { label: 'Na medida 40x29 cm (folha com adesivos)', preco: 98.00 },
          { label: 'Cartela A4 · 29x20 cm', preco: 55.00 },
          { label: 'Cartela A3 · 29x40 cm', preco: 85.00 },
          { label: 'Meio metro', preco: 110.00 },
          { label: '1 metro', preco: 135.00 },
        ],
        faq: [
          { p: 'O que é o Adesivo DTF UV?', r: 'É um adesivo personalizado produzido com tecnologia DTF UV, que oferece alta definição, brilho e acabamento premium.' },
          { p: 'Quais tamanhos estão disponíveis?', r: 'Trabalhamos com cartelas nos tamanhos A4 e A3.' },
          { p: 'Onde posso aplicar os adesivos DTF UV?', r: 'Eles podem ser aplicados em brindes, embalagens, copos, papelaria criativa e diversos produtos personalizados.' },
        ] },
      { bg: 'linear-gradient(135deg,#bbf7d0,#16a34a)', badge: 'Novo',
        imagem: 'img/adesivo-brilha-escuro.webp',
        nome: 'Adesivo Brilha no Escuro',
        spec: 'Adesivo que brilha no escuro · escolha o formato ou a cartela',
        prazo: 7,
        variacoes: [
          { label: '204x184 mm', preco: 35.00 },
          { label: '279x204 mm', preco: 45.00 },
          { label: '434x279 mm', preco: 55.00 },
          { label: '5 cartelas · 20,4x18,4 cm', preco: 80.00 },
          { label: '5 cartelas · 279x204 mm', preco: 105.00 },
          { label: '5 cartelas · 434x279 mm', preco: 135.00 },
        ] },
      { bg: 'linear-gradient(135deg,#a7f3d0,#059669)', badge: 'Novo',
        imagem: 'img/adesivo-cartao-credito.webp',
        nome: 'Adesivo para Cartão de Crédito',
        spec: 'Adesivo personalizado para cartão/máquina · preço menor no atacado',
        prazo: 2,
        variacoes: [
          { label: '1 un', preco: 25.90 },
          { label: '5 un', preco: 21.99 },
          { label: '10 un', preco: 23.99 },
          { label: '20 un', preco: 31.99 },
          { label: '30 un', preco: 36.99 },
          { label: '50 un', preco: 47.99 },
          { label: '100 un', preco: 72.99 },
        ] },
    ],
  },

  'brindes': {
    nome: 'Brindes',
    emoji: '🎁',
    banner: 'linear-gradient(120deg,#be185d,#ec4899)',
    descricao: 'Brindes personalizados que mantêm sua marca na memória (e na mão) dos clientes.',
    produtos: [
      { bg: 'linear-gradient(135deg,#fecaca,#dc2626)', badge: 'Novo', destaque: true,
        nome: 'Kit Balde 6L + Copos 350ml',
        spec: 'Balde de 6 litros + copos de 350ml · impressão colorida só frente (4x0) · pedido mínimo 5 unidades',
        unidade: 'kit', unidadePlural: 'kits',
        minimoTotal: 5,
        opcoesCombinacao: [
          { nome: 'Kit Balde + Copos', faixas: [{ min: 1, preco: 59.90 }] },
        ] },
      chineloPersonalizado,
      copoCuia,
      canetaPersonalizada,
      { emoji: '🔑', bg: 'linear-gradient(135deg,#fecdd3,#fb7185)',
        nome: 'Chaveiro Acrílico', spec: 'Formato personalizado · impressão UV',
        variacoes: [
          { label: '50 un', preco: 89.90 },
          { label: '100 un', preco: 149.90 },
          { label: '200 un', preco: 259.90 },
        ] },
      { emoji: '👜', bg: 'linear-gradient(135deg,#fecaca,#ef4444)',
        nome: 'Ecobag Algodão', spec: 'Algodão cru · serigrafia 1 cor',
        variacoes: [
          { label: '25 un', preco: 169.90 },
          { label: '50 un', preco: 299.90 },
          { label: '100 un', preco: 529.90 },
        ] },
    ],
  },

  'embalagens': {
    nome: 'Embalagens',
    emoji: '📦',
    banner: 'linear-gradient(120deg,#9a3412,#f97316)',
    descricao: 'Embalagens personalizadas que valorizam seu produto do delivery à prateleira.',
    produtos: [
      caixaPresente,
      forminhasDoces,
      caixinhaMilk,
      sacolaSilk,
      sacolaPlastica,
      sacolaCordao,
      { emoji: '🛍️', bg: 'linear-gradient(135deg,#ffedd5,#fb923c)',
        nome: 'Sacola de Papel', spec: 'Alça torcida · impressão 4x0',
        variacoes: [
          { label: '100 un', preco: 249.90 },
          { label: '250 un', preco: 549.90 },
          { label: '500 un', preco: 949.90 },
        ] },
      { emoji: '🥖', bg: 'linear-gradient(135deg,#fde68a,#d97706)',
        nome: 'Saco Kraft com Janela', spec: 'Ideal para alimentos · visor transparente',
        variacoes: [
          { label: '250 un', preco: 179.90 },
          { label: '500 un', preco: 299.90 },
          { label: '1.000 un', preco: 499.90 },
        ] },
      { emoji: '🎀', bg: 'linear-gradient(135deg,#fef3c7,#f59e0b)',
        nome: 'Fita Adesiva Personalizada', spec: 'Sua marca em cada pacote',
        variacoes: [
          { label: '10 rolos', preco: 129.90 },
          { label: '25 rolos', preco: 279.90 },
          { label: '50 rolos', preco: 489.90 },
        ] },
    ],
  },

  'cardapios': {
    nome: 'Cardápios',
    emoji: '📖',
    banner: 'linear-gradient(120deg,#7c2d12,#f97316)',
    descricao: 'Cardápios personalizados para o seu restaurante, bar ou delivery.',
    produtos: [
      { bg: 'linear-gradient(135deg,#fed7aa,#c2410c)', badge: 'Novo', prazo: 3, destaque: true,
        nome: 'Cardápio Mini com Wire-o 14,4x14,4 cm',
        spec: 'PVC 0,3mm branco · 4x4 brilho/UV total frente e verso · 14,4x14,4 cm · 4 páginas · acabamento wire-o (duplo anel)',
        arteNota: 'Criação da arte do cardápio: R$ 45,00.',
        variacoes: [
          { label: '5 un', preco: 186.90 },
          { label: '10 un', preco: 228.90 },
          { label: '25 un', preco: 379.90 },
          { label: '50 un', preco: 651.90 },
          { label: '100 un', preco: 1179.90 },
        ] },
    ],
  },

  'quadros': {
    nome: 'Quadros',
    emoji: '🖼️',
    banner: 'linear-gradient(120deg,#78350f,#b45309)',
    descricao: 'Quadros decorativos personalizados com a sua arte.',
    produtos: [
      { bg: 'linear-gradient(135deg,#fde68a,#92400e)', badge: 'Novo', destaque: true,
        nome: 'Quadro MDF 3mm 20x30 cm',
        spec: 'MDF 3mm com adesivo · colorido só frente · laminação fosca · 20x30 cm · escolha a fixação',
        grupoLabel: 'Fixação', opcaoLabel: 'Quantidade',
        tamanhos: {
          'Presilha para Pendurar': [
            { label: '1 un', preco: 30.90 },
            { label: '5 un', preco: 142.90 },
            { label: '10 un', preco: 268.90 },
            { label: '20 un', preco: 504.90 },
            { label: '30 un', preco: 756.90 },
            { label: '50 un', preco: 1102.90 },
          ],
          'Fita Dupla Face (4 cantos)': [
            { label: '1 un', preco: 30.90 },
            { label: '5 un', preco: 142.90 },
            { label: '10 un', preco: 268.90 },
            { label: '20 un', preco: 504.90 },
            { label: '30 un', preco: 756.90 },
            { label: '50 un', preco: 1102.90 },
          ],
        } },
    ],
  },

  'ponto-de-venda': {
    nome: 'Ponto de Venda',
    emoji: '🪧',
    banner: 'linear-gradient(120deg,#0e7490,#06b6d4)',
    descricao: 'Banners, displays e materiais de PDV para destacar sua marca onde a venda acontece.',
    produtos: [
      { emoji: '🪧', bg: 'linear-gradient(135deg,#a5f3fc,#06b6d4)', badge: 'Novo', destaque: true,
        imagem: 'img/banner-lona.webp',
        nome: 'Banner Lona Brilho 440g',
        spec: 'Lona brilho 440g · colorido só frente · já com bastão e corda · escolha o formato',
        variacoes: [
          { label: '0,45 x 0,65 m', preco: 23.90 },
          { label: '0,62 x 0,80 m', preco: 26.90 },
          { label: '0,52 x 0,90 m', preco: 30.90 },
          { label: '0,79 x 1,20 m', preco: 56.90 },
          { label: '0,90 x 1,20 m', preco: 65.90 },
          { label: '1,05 x 1,20 m', preco: 75.90 },
          { label: '1,05 x 1,50 m', preco: 90.90 },
          { label: 'Medida personalizada', preco: null },
        ] },
      { emoji: '🖼️', bg: 'linear-gradient(135deg,#bae6fd,#38bdf8)',
        nome: 'Display de Mesa', spec: 'Papel triplex 350g · faca especial',
        variacoes: [
          { label: '10 un', preco: 89.90 },
          { label: '25 un', preco: 169.90 },
          { label: '50 un', preco: 279.90 },
        ] },
      { emoji: '💬', bg: 'linear-gradient(135deg,#a5f3fc,#0ea5e9)',
        nome: 'Wobbler', spec: 'Chame atenção na gôndola',
        variacoes: [
          { label: '50 un', preco: 69.90 },
          { label: '100 un', preco: 109.90 },
          { label: '250 un', preco: 199.90 },
        ] },
      { bg: 'linear-gradient(135deg,#a7f3d0,#059669)', badge: 'Novo',
        imagem: 'img/display-acrilico.webp',
        nome: 'Display em Acrílico (Arte Única)',
        spec: 'Acrílico cristal 2mm · colorido só frente · UV direta · arte única · escolha a orientação e a quantidade',
        grupoLabel: 'Orientação', opcaoLabel: 'Quantidade',
        tamanhos: {
          '15x10 cm horizontal': [
            { label: '1 un', preco: 32.90 },
            { label: '5 un', preco: 142.90 },
            { label: '10 un', preco: 269.90 },
            { label: '25 un', preco: 599.90 },
          ],
          '10x15 cm vertical': [
            { label: '1 un', preco: 32.90 },
            { label: '5 un', preco: 142.90 },
            { label: '10 un', preco: 269.90 },
            { label: '25 un', preco: 599.90 },
          ],
        } },
      { bg: 'linear-gradient(135deg,#fde68a,#b45309)', badge: 'Novo',
        nome: 'Cubo de Papel',
        spec: 'Couchê 300g · colorido só frente · UV total · 8x8 cm',
        variacoes: [
          { label: '50 un', preco: 867.90 },
          { label: '100 un', preco: 1288.90 },
          { label: '250 un', preco: 1786.90 },
          { label: '500 un', preco: 2049.90 },
          { label: '1.000 un', preco: 2773.90 },
        ] },
      { bg: 'linear-gradient(135deg,#c7d2fe,#4338ca)', badge: 'Novo',
        nome: 'Display de Retrovisor',
        spec: 'Couchê 300g · colorido só frente · UV total frente e verso · 8,5x19,88 cm',
        variacoes: [
          { label: '10 un', preco: 68.90 },
          { label: '25 un', preco: 157.90 },
          { label: '50 un', preco: 208.90 },
          { label: '100 un', preco: 382.90 },
          { label: '250 un', preco: 417.90 },
          { label: '500 un', preco: 457.90 },
          { label: '1.000 un', preco: 622.90 },
        ] },
      bolsaHaste,
      { bg: 'linear-gradient(135deg,#f9a8d4,#be185d)', badge: 'Novo', destaque: true,
        imagem: 'img/backdrop.webp',
        nome: 'Backdrop em Lona Brilho Frontlight 440g',
        spec: 'Lona brilho frontlight 440g · acabamento em ilhós · escolha o tamanho',
        variacoes: [
          { label: '2,00 x 2,00 m', preco: 190.00 },
          { label: '1,80 x 2,50 m', preco: 220.00 },
          { label: '1,80 x 3,00 m', preco: 266.00 },
          { label: '2,50 x 2,50 m', preco: 298.00 },
          { label: '3,00 x 3,00 m', preco: 498.00 },
          { label: 'Outra medida', preco: null },
        ] },
    ],
  },

  'wind-banner': {
    nome: 'Wind Banner',
    emoji: '🚩',
    banner: 'linear-gradient(120deg,#0369a1,#38bdf8)',
    descricao: 'Wind banners (bandeiras de vento) para divulgar sua marca em eventos, lojas e calçadas. Escolha a base e o tamanho.',
    produtos: [
      { emoji: '🚩', bg: 'linear-gradient(135deg,#bae6fd,#0284c7)', badge: 'Novo', destaque: true,
        nome: 'Wind Banner Personalizado',
        spec: 'Tecido com impressão colorida · kit completo com mastro · escolha a base e o tamanho',
        grupoLabel: 'Base', opcaoLabel: 'Tamanho',
        tamanhos: {
          'Com base plástica': [
            { label: '1,50 × 0,50 m', preco: 184.85 },
            { label: '2,00 × 0,75 m', preco: 207.35 },
            { label: '2,20 × 0,75 m', preco: 214.85 },
            { label: '2,50 × 0,75 m', preco: 222.35 },
            { label: '3,00 × 0,75 m', preco: 237.35 },
          ],
          'Com base de concreto': [
            { label: '1,50 × 0,50 m', preco: 139.85 },
            { label: '2,00 × 0,75 m', preco: 162.35 },
            { label: '2,20 × 0,75 m', preco: 169.85 },
            { label: '2,50 × 0,75 m', preco: 177.35 },
            { label: '3,00 × 0,75 m', preco: 192.35 },
          ],
        } },
    ],
  },

  'copos': {
    nome: 'Copos',
    emoji: '🥤',
    banner: 'linear-gradient(120deg,#065f46,#10b981)',
    descricao: 'Copos personalizados para brindes, eventos, bares e delivery.',
    produtos: [
      copoCuia,
      { bg: 'linear-gradient(135deg,#e0f2fe,#0ea5e9)', badge: 'Novo', destaque: true,
        imagem: 'img/taca-gin.webp',
        nome: 'Taça de Gin Personalizada',
        spec: 'Taça de gin · personalização em DTF UV só frente · Mais quantidades: consultar valor no atacado.',
        variacoes: [
          { label: '1 un', preco: 10.00 },
        ] },
      copoInoxColorido,
      copoTermico,
    ],
  },

  'gravacao-a-laser': {
    nome: 'Gravação a Laser',
    emoji: '🔆',
    banner: 'linear-gradient(120deg,#334155,#64748b)',
    descricao: 'Personalização premium com gravação a laser em metal, inox e outros materiais.',
    produtos: [
      copoCuia,
      kitChurrasco,
      { bg: 'linear-gradient(135deg,#d6d3d1,#78716c)', badge: 'Novo', destaque: true,
        imagem: 'img/gravacao-mdf.webp',
        nome: 'Gravação a Laser em MDF (item do cliente)',
        spec: 'Gravação a laser 4x0 em item de MDF trazido pelo cliente · até 30 cm · 10+ itens R$ 15,90/un · menos de 10 itens R$ 25,00/un',
        prazoTexto: 'de 3 a 5 dias úteis',
        unidade: 'item', unidadePlural: 'itens',
        opcoesCombinacao: [
          { nome: 'Gravação a Laser', faixas: [
            { min: 1, preco: 25.00 },
            { min: 10, preco: 15.90 },
          ] },
        ] },
      { emoji: '🖋️', bg: 'linear-gradient(135deg,#cbd5e1,#475569)', badge: 'Novo',
        nome: 'Caneta de Metal Touch', spec: 'Metal · ponta touch · gravação a laser 4x0 (0,6x5 cm)',
        variacoes: [
          { label: '1 un', preco: 10.90 },
          { label: 'Combo 10 un', preco: 98.90 },
        ] },
      { bg: 'linear-gradient(135deg,#e2e8f0,#64748b)', badge: 'Novo',
        imagem: 'img/caneta-slim-touch.webp',
        nome: 'Caneta de Metal Slim Touch',
        spec: 'Metal slim · ponta touch · gravação a laser 4x0 (4x0,4 cm) · 5 cores · Consultar as cores disponíveis.',
        variacoes: [
          { label: '10 un', preco: 97.90 },
          { label: '20 un', preco: 179.90 },
          { label: '50 un', preco: 412.90 },
          { label: '100 un', preco: 809.90 },
          { label: '250 un', preco: 2024.90 },
          { label: '500 un', preco: 4012.90 },
          { label: '1.000 un', preco: 7949.90 },
        ] },
      { emoji: '🍾', bg: 'linear-gradient(135deg,#d1d5db,#4b5563)', badge: 'Novo',
        imagem: 'img/chaveiro-abridor.webp',
        nome: 'Chaveiro Abridor de Metal — Garrafa',
        spec: 'Metal · abridor de garrafa · gravação a laser 4x0 (3,8x0,7 cm)',
        precoUnitario: 2.50,
        minimo: 25,
        cores: ['Preto', 'Verde', 'Vermelho', 'Rosa', 'Azul', 'Prata'] },
      copoInoxColorido,
      garrafaInox750,
      squeezeFosca,
      copoTermico,
      canetaPersonalizada,
    ],
  },

  'dtf': {
    nome: 'DTF',
    emoji: '👕',
    banner: 'linear-gradient(120deg,#6d28d9,#c026d3)',
    descricao: 'Estampas em DTF e DTF rígido com cores vibrantes, em tecidos e superfícies rígidas.',
    produtos: [
      kitChurrasco,
      copoCuia,
      camisetaDtf,
    ],
  },

  'textil': {
    nome: 'Linha Têxtil',
    emoji: '👕',
    banner: 'linear-gradient(120deg,#9d174d,#ec4899)',
    descricao: 'Camisetas, moletons, ecobags, toalhas e outros itens em tecido personalizados.',
    produtos: [
      jaquetaMisty,
      camisaCopa,
      camisaAmericana,
      camisaCiclismo,
      poloBordada,
      moletomCanguru,
      camisaPesca,
      camisetaDryMasc,
      camisetaDryFem,
      camisetaDtf,
      ecobagPersonalizada,
      cordaoPersonalizado,
      toalhaBanho,
      toalhaRosto,
    ],
  },

  'lancamentos': {
    nome: 'Lançamentos',
    emoji: '🔥',
    banner: 'linear-gradient(120deg,#7c3aed,#a78bfa)',
    descricao: 'As novidades que acabaram de chegar na Print House.',
    produtos: [
      camisetaDtf,
      kitChurrasco,
      copoTermico,
    ],
  },
};

/* Sobrescreve o catálogo com as edições feitas no painel administrativo
   (admin.html) — apenas se forem da versão atual do catálogo. Edições de
   versões antigas são descartadas para não esconder produtos novos. */
try {
  const catalogoEditado = localStorage.getItem('printhouse_catalogo');
  if (catalogoEditado) {
    const dados = JSON.parse(catalogoEditado);
    if (dados && dados.versao === CATALOGO_VERSAO && dados.catalogo && typeof dados.catalogo === 'object') {
      Object.keys(CATALOGO).forEach((k) => delete CATALOGO[k]);
      Object.assign(CATALOGO, dados.catalogo);
    } else {
      localStorage.removeItem('printhouse_catalogo');
    }
  }
} catch (e) { /* mantém o catálogo padrão */ }
